logging:
  level: "DEBUG"
  file: "log/ai_talkshow.log"
  max_size: 10485760  # 10MB
  backup_count: 5

bilibili:
  live_room_ids: [23679394]
  session: ""  # 从环境变量 BILIBILI_SESSION 获取

models:
  ai1:
    nickname: "小千"
    type: "qwen"
    api_key: ""  # 从环境变量 QWEN_API_KEY 获取
    model: "qwen-plus-0112"
    max_history: 2
    tts_voice: "zh-CN-XiaoxiaoNeural"
    vts_port: "8001"

  ai2:
    nickname: "小问"
    type: "qwen"
    api_key: ""  # 从环境变量 QWEN_API_KEY 获取
    model: "qwen-plus-0112"
    max_history: 2
    tts_voice: "zh-CN-XiaoyiNeural"
    vts_port: "8003"

debate:
  max_turns: 5
  topics:
    main: "考公是应届生最好的选择吗？"
    ai1: "考公是应届生最好的选择！"
    ai2: "考公并不是应届生最好的选择！"
